-- ============================================================
-- Seed: +300 words (100 easy / 100 medium / 100 hard)
-- Slugs must match categories seeded in 002_seed_data.sql
-- ============================================================

INSERT INTO public.words (category_id, word_en, word_id, difficulty)
SELECT c.id, v.word_en, v.word_id, v.difficulty
FROM (VALUES
  -- ---------------- EASY (100) ----------------
  ('hewan', 'Lion', 'Singa', 'easy'),
  ('hewan', 'Tiger', 'Harimau', 'easy'),
  ('hewan', 'Bear', 'Beruang', 'easy'),
  ('hewan', 'Rabbit', 'Kelinci', 'easy'),
  ('hewan', 'Horse', 'Kuda', 'easy'),
  ('hewan', 'Cow', 'Sapi', 'easy'),
  ('hewan', 'Goat', 'Kambing', 'easy'),
  ('hewan', 'Chicken', 'Ayam', 'easy'),
  ('hewan', 'Duck', 'Bebek', 'easy'),
  ('hewan', 'Snake', 'Ular', 'easy'),
  ('hewan', 'Frog', 'Katak', 'easy'),
  ('hewan', 'Monkey', 'Monyet', 'easy'),
  ('hewan', 'Bird', 'Burung', 'easy'),
  ('hewan', 'Mouse', 'Tikus', 'easy'),
  ('hewan', 'Bee', 'Lebah', 'easy'),
  ('hewan', 'Ant', 'Semut', 'easy'),
  ('hewan', 'Spider', 'Laba-laba', 'easy'),
  ('hewan', 'Turtle', 'Kura-kura', 'easy'),
  ('hewan', 'Whale', 'Paus', 'easy'),
  ('hewan', 'Sheep', 'Domba', 'easy'),
  ('makanan', 'Bread', 'Roti', 'easy'),
  ('makanan', 'Noodle', 'Mie', 'easy'),
  ('makanan', 'Egg', 'Telur', 'easy'),
  ('makanan', 'Cheese', 'Keju', 'easy'),
  ('makanan', 'Soup', 'Sup', 'easy'),
  ('makanan', 'Cake', 'Kue', 'easy'),
  ('makanan', 'Ice Cream', 'Es Krim', 'easy'),
  ('makanan', 'Meatball', 'Bakso', 'easy'),
  ('makanan', 'Fried Rice', 'Nasi Goreng', 'easy'),
  ('makanan', 'Milk', 'Susu', 'easy'),
  ('buah', 'Orange', 'Jeruk', 'easy'),
  ('buah', 'Mango', 'Mangga', 'easy'),
  ('buah', 'Grape', 'Anggur', 'easy'),
  ('buah', 'Watermelon', 'Semangka', 'easy'),
  ('buah', 'Strawberry', 'Stroberi', 'easy'),
  ('buah', 'Pineapple', 'Nanas', 'easy'),
  ('buah', 'Papaya', 'Pepaya', 'easy'),
  ('buah', 'Coconut', 'Kelapa', 'easy'),
  ('buah', 'Melon', 'Melon', 'easy'),
  ('buah', 'Guava', 'Jambu', 'easy'),
  ('kendaraan', 'Motorcycle', 'Motor', 'easy'),
  ('kendaraan', 'Bus', 'Bus', 'easy'),
  ('kendaraan', 'Train', 'Kereta', 'easy'),
  ('kendaraan', 'Boat', 'Perahu', 'easy'),
  ('kendaraan', 'Ship', 'Kapal', 'easy'),
  ('kendaraan', 'Truck', 'Truk', 'easy'),
  ('kendaraan', 'Taxi', 'Taksi', 'easy'),
  ('benda', 'Table', 'Meja', 'easy'),
  ('benda', 'Door', 'Pintu', 'easy'),
  ('benda', 'Window', 'Jendela', 'easy'),
  ('benda', 'Book', 'Buku', 'easy'),
  ('benda', 'Pencil', 'Pensil', 'easy'),
  ('benda', 'Bag', 'Tas', 'easy'),
  ('benda', 'Bottle', 'Botol', 'easy'),
  ('benda', 'Spoon', 'Sendok', 'easy'),
  ('benda', 'Fork', 'Garpu', 'easy'),
  ('benda', 'Knife', 'Pisau', 'easy'),
  ('benda', 'Cup', 'Gelas', 'easy'),
  ('benda', 'Plate', 'Piring', 'easy'),
  ('benda', 'Bed', 'Kasur', 'easy'),
  ('benda', 'Lamp', 'Lampu', 'easy'),
  ('benda', 'Key', 'Kunci', 'easy'),
  ('benda', 'Ball', 'Bola', 'easy'),
  ('benda', 'Shoe', 'Sepatu', 'easy'),
  ('benda', 'Hat', 'Topi', 'easy'),
  ('benda', 'Glasses', 'Kacamata', 'easy'),
  ('benda', 'Star', 'Bintang', 'easy'),
  ('benda', 'Moon', 'Bulan', 'easy'),
  ('benda', 'Cloud', 'Awan', 'easy'),
  ('benda', 'Rain', 'Hujan', 'easy'),
  ('benda', 'Flower', 'Bunga', 'easy'),
  ('benda', 'Tree', 'Pohon', 'easy'),
  ('benda', 'Grass', 'Rumput', 'easy'),
  ('benda', 'Mountain', 'Gunung', 'easy'),
  ('benda', 'River', 'Sungai', 'easy'),
  ('benda', 'Sea', 'Laut', 'easy'),
  ('benda', 'Fire', 'Api', 'easy'),
  ('benda', 'Snow', 'Salju', 'easy'),
  ('benda', 'Leaf', 'Daun', 'easy'),
  ('benda', 'Sun', 'Matahari', 'easy'),
  ('olahraga', 'Swimming', 'Renang', 'easy'),
  ('olahraga', 'Running', 'Lari', 'easy'),
  ('olahraga', 'Boxing', 'Tinju', 'easy'),
  ('olahraga', 'Tennis', 'Tenis', 'easy'),
  ('olahraga', 'Volleyball', 'Voli', 'easy'),
  ('musik', 'Flute', 'Seruling', 'easy'),
  ('musik', 'Violin', 'Biola', 'easy'),
  ('musik', 'Trumpet', 'Terompet', 'easy'),
  ('teknologi', 'Television', 'Televisi', 'easy'),
  ('teknologi', 'Radio', 'Radio', 'easy'),
  ('teknologi', 'Keyboard', 'Keyboard', 'easy'),
  ('teknologi', 'Mouse', 'Mouse', 'easy'),
  ('profesi', 'Police', 'Polisi', 'easy'),
  ('profesi', 'Farmer', 'Petani', 'easy'),
  ('profesi', 'Chef', 'Koki', 'easy'),
  ('profesi', 'Fireman', 'Pemadam', 'easy'),
  ('profesi', 'Nurse', 'Perawat', 'easy'),
  ('profesi', 'Soldier', 'Tentara', 'easy'),
  ('kartun', 'Mickey', 'Miki', 'easy'),
  ('kartun', 'Hello Kitty', 'Hello Kitty', 'easy'),

  -- ---------------- MEDIUM (100) ----------------
  ('hewan', 'Kangaroo', 'Kanguru', 'medium'),
  ('hewan', 'Penguin', 'Penguin', 'medium'),
  ('hewan', 'Dolphin', 'Lumba-lumba', 'medium'),
  ('hewan', 'Peacock', 'Merak', 'medium'),
  ('hewan', 'Owl', 'Burung Hantu', 'medium'),
  ('hewan', 'Squirrel', 'Tupai', 'medium'),
  ('hewan', 'Hedgehog', 'Landak', 'medium'),
  ('hewan', 'Seahorse', 'Kuda Laut', 'medium'),
  ('hewan', 'Flamingo', 'Flamingo', 'medium'),
  ('hewan', 'Jellyfish', 'Ubur-ubur', 'medium'),
  ('hewan', 'Rhinoceros', 'Badak', 'medium'),
  ('hewan', 'Crocodile', 'Buaya', 'medium'),
  ('hewan', 'Camel', 'Unta', 'medium'),
  ('hewan', 'Panda', 'Panda', 'medium'),
  ('hewan', 'Koala', 'Koala', 'medium'),
  ('makanan', 'Hamburger', 'Hamburger', 'medium'),
  ('makanan', 'Spaghetti', 'Spageti', 'medium'),
  ('makanan', 'Dumpling', 'Pangsit', 'medium'),
  ('makanan', 'Pancake', 'Panekuk', 'medium'),
  ('makanan', 'Donut', 'Donat', 'medium'),
  ('makanan', 'Gado-gado', 'Gado-gado', 'medium'),
  ('makanan', 'Fried Chicken', 'Ayam Goreng', 'medium'),
  ('makanan', 'Sandwich', 'Roti Lapis', 'medium'),
  ('makanan', 'Popcorn', 'Berondong', 'medium'),
  ('makanan', 'Pudding', 'Puding', 'medium'),
  ('buah', 'Kiwi', 'Kiwi', 'medium'),
  ('buah', 'Lychee', 'Leci', 'medium'),
  ('buah', 'Avocado', 'Alpukat', 'medium'),
  ('buah', 'Pomegranate', 'Delima', 'medium'),
  ('buah', 'Starfruit', 'Belimbing', 'medium'),
  ('kendaraan', 'Ambulance', 'Ambulans', 'medium'),
  ('kendaraan', 'Tractor', 'Traktor', 'medium'),
  ('kendaraan', 'Scooter', 'Skuter', 'medium'),
  ('kendaraan', 'Sailboat', 'Perahu Layar', 'medium'),
  ('kendaraan', 'Rocket', 'Roket', 'medium'),
  ('negara', 'Egypt', 'Mesir', 'medium'),
  ('negara', 'Australia', 'Australia', 'medium'),
  ('negara', 'Germany', 'Jerman', 'medium'),
  ('negara', 'Italy', 'Italia', 'medium'),
  ('negara', 'India', 'India', 'medium'),
  ('kota', 'London', 'London', 'medium'),
  ('kota', 'Bandung', 'Bandung', 'medium'),
  ('kota', 'Surabaya', 'Surabaya', 'medium'),
  ('kota', 'New York', 'New York', 'medium'),
  ('kota', 'Rome', 'Roma', 'medium'),
  ('profesi', 'Scientist', 'Ilmuwan', 'medium'),
  ('profesi', 'Engineer', 'Insinyur', 'medium'),
  ('profesi', 'Journalist', 'Wartawan', 'medium'),
  ('profesi', 'Photographer', 'Fotografer', 'medium'),
  ('profesi', 'Detective', 'Detektif', 'medium'),
  ('film', 'Frozen', 'Frozen', 'medium'),
  ('film', 'Batman', 'Batman', 'medium'),
  ('film', 'Jurassic Park', 'Jurassic Park', 'medium'),
  ('film', 'Harry Potter', 'Harry Potter', 'medium'),
  ('film', 'Toy Story', 'Toy Story', 'medium'),
  ('game', 'Fortnite', 'Fortnite', 'medium'),
  ('game', 'Roblox', 'Roblox', 'medium'),
  ('game', 'Valorant', 'Valorant', 'medium'),
  ('game', 'Tetris', 'Tetris', 'medium'),
  ('game', 'Pac-Man', 'Pac-Man', 'medium'),
  ('anime', 'Pokemon', 'Pokemon', 'medium'),
  ('anime', 'Dragon Ball', 'Dragon Ball', 'medium'),
  ('anime', 'Attack on Titan', 'Attack on Titan', 'medium'),
  ('anime', 'My Hero Academia', 'My Hero Academia', 'medium'),
  ('anime', 'Jujutsu Kaisen', 'Jujutsu Kaisen', 'medium'),
  ('teknologi', 'Laptop', 'Laptop', 'medium'),
  ('teknologi', 'Printer', 'Printer', 'medium'),
  ('teknologi', 'Drone', 'Drone', 'medium'),
  ('teknologi', 'Satellite', 'Satelit', 'medium'),
  ('teknologi', 'Headphone', 'Headphone', 'medium'),
  ('benda', 'Compass', 'Kompas', 'medium'),
  ('benda', 'Anchor', 'Jangkar', 'medium'),
  ('benda', 'Ladder', 'Tangga', 'medium'),
  ('benda', 'Hammer', 'Palu', 'medium'),
  ('benda', 'Scissors', 'Gunting', 'medium'),
  ('benda', 'Candle', 'Lilin', 'medium'),
  ('benda', 'Mirror', 'Cermin', 'medium'),
  ('benda', 'Bucket', 'Ember', 'medium'),
  ('benda', 'Balloon', 'Balon', 'medium'),
  ('benda', 'Kite', 'Layang-layang', 'medium'),
  ('olahraga', 'Skateboarding', 'Skateboard', 'medium'),
  ('olahraga', 'Surfing', 'Selancar', 'medium'),
  ('olahraga', 'Cycling', 'Bersepeda', 'medium'),
  ('olahraga', 'Golf', 'Golf', 'medium'),
  ('olahraga', 'Karate', 'Karate', 'medium'),
  ('musik', 'Harp', 'Harpa', 'medium'),
  ('musik', 'Accordion', 'Akordeon', 'medium'),
  ('musik', 'Xylophone', 'Xilofon', 'medium'),
  ('musik', 'Microphone', 'Mikrofon', 'medium'),
  ('musik', 'Trombone', 'Trombon', 'medium'),
  ('tokoh', 'Newton', 'Newton', 'medium'),
  ('tokoh', 'Gandhi', 'Gandhi', 'medium'),
  ('tokoh', 'Napoleon', 'Napoleon', 'medium'),
  ('tokoh', 'Habibie', 'Habibie', 'medium'),
  ('tokoh', 'Kartini', 'Kartini', 'medium'),
  ('kartun', 'Tom and Jerry', 'Tom and Jerry', 'medium'),
  ('kartun', 'Pikachu', 'Pikachu', 'medium'),
  ('kartun', 'Upin Ipin', 'Upin Ipin', 'medium'),
  ('kartun', 'Shaun the Sheep', 'Shaun the Sheep', 'medium'),
  ('kartun', 'Minions', 'Minions', 'medium'),

  -- ---------------- HARD (100) ----------------
  ('profesi', 'Anesthesiologist', 'Ahli Anestesi', 'hard'),
  ('profesi', 'Meteorologist', 'Ahli Meteorologi', 'hard'),
  ('profesi', 'Cartographer', 'Kartografer', 'hard'),
  ('profesi', 'Philosopher', 'Filsuf', 'hard'),
  ('profesi', 'Diplomat', 'Diplomat', 'hard'),
  ('profesi', 'Neurosurgeon', 'Ahli Bedah Saraf', 'hard'),
  ('profesi', 'Seismologist', 'Ahli Seismologi', 'hard'),
  ('profesi', 'Choreographer', 'Koreografer', 'hard'),
  ('profesi', 'Taxidermist', 'Ahli Awetan', 'hard'),
  ('profesi', 'Sommelier', 'Sommelier', 'hard'),
  ('teknologi', 'Blockchain', 'Blockchain', 'hard'),
  ('teknologi', 'Algorithm', 'Algoritma', 'hard'),
  ('teknologi', 'Encryption', 'Enkripsi', 'hard'),
  ('teknologi', 'Semiconductor', 'Semikonduktor', 'hard'),
  ('teknologi', 'Cybersecurity', 'Keamanan Siber', 'hard'),
  ('teknologi', 'Nanotechnology', 'Nanoteknologi', 'hard'),
  ('teknologi', 'Hologram', 'Hologram', 'hard'),
  ('teknologi', 'Quantum Computer', 'Komputer Kuantum', 'hard'),
  ('teknologi', 'Neural Network', 'Jaringan Saraf', 'hard'),
  ('teknologi', 'Firewall', 'Firewall', 'hard'),
  ('benda', 'Chandelier', 'Lampu Gantung', 'hard'),
  ('benda', 'Hourglass', 'Jam Pasir', 'hard'),
  ('benda', 'Kaleidoscope', 'Kaleidoskop', 'hard'),
  ('benda', 'Metronome', 'Metronom', 'hard'),
  ('benda', 'Stethoscope', 'Stetoskop', 'hard'),
  ('benda', 'Periscope', 'Periskop', 'hard'),
  ('benda', 'Barometer', 'Barometer', 'hard'),
  ('benda', 'Gyroscope', 'Giroskop', 'hard'),
  ('benda', 'Sundial', 'Jam Matahari', 'hard'),
  ('benda', 'Astrolabe', 'Astrolab', 'hard'),
  ('benda', 'Seismograph', 'Seismograf', 'hard'),
  ('benda', 'Defibrillator', 'Defibrilator', 'hard'),
  ('benda', 'Centrifuge', 'Sentrifugal', 'hard'),
  ('benda', 'Spectrometer', 'Spektrometer', 'hard'),
  ('benda', 'Lighthouse', 'Mercusuar', 'hard'),
  ('benda', 'Windmill', 'Kincir Angin', 'hard'),
  ('benda', 'Aqueduct', 'Saluran Air', 'hard'),
  ('benda', 'Catapult', 'Ketapel', 'hard'),
  ('benda', 'Trebuchet', 'Trebuchet', 'hard'),
  ('benda', 'Guillotine', 'Guillotine', 'hard'),
  ('hewan', 'Platypus', 'Platipus', 'hard'),
  ('hewan', 'Armadillo', 'Armadillo', 'hard'),
  ('hewan', 'Narwhal', 'Narwal', 'hard'),
  ('hewan', 'Axolotl', 'Axolotl', 'hard'),
  ('hewan', 'Pangolin', 'Trenggiling', 'hard'),
  ('hewan', 'Tarantula', 'Tarantula', 'hard'),
  ('hewan', 'Salamander', 'Salamander', 'hard'),
  ('hewan', 'Cassowary', 'Kasuari', 'hard'),
  ('hewan', 'Wolverine', 'Wolverine', 'hard'),
  ('hewan', 'Mongoose', 'Garangan', 'hard'),
  ('hewan', 'Okapi', 'Okapi', 'hard'),
  ('hewan', 'Quokka', 'Quokka', 'hard'),
  ('hewan', 'Capybara', 'Kapibara', 'hard'),
  ('hewan', 'Manatee', 'Manate', 'hard'),
  ('hewan', 'Chameleon', 'Bunglon', 'hard'),
  ('makanan', 'Ratatouille', 'Ratatouille', 'hard'),
  ('makanan', 'Bruschetta', 'Bruschetta', 'hard'),
  ('makanan', 'Tiramisu', 'Tiramisu', 'hard'),
  ('makanan', 'Guacamole', 'Guacamole', 'hard'),
  ('makanan', 'Quiche', 'Quiche', 'hard'),
  ('makanan', 'Paella', 'Paella', 'hard'),
  ('makanan', 'Gnocchi', 'Gnocchi', 'hard'),
  ('makanan', 'Macaron', 'Makaron', 'hard'),
  ('makanan', 'Escargot', 'Escargot', 'hard'),
  ('makanan', 'Baklava', 'Baklava', 'hard'),
  ('negara', 'Kazakhstan', 'Kazakhstan', 'hard'),
  ('negara', 'Madagascar', 'Madagaskar', 'hard'),
  ('negara', 'Luxembourg', 'Luksemburg', 'hard'),
  ('negara', 'Kyrgyzstan', 'Kirgizstan', 'hard'),
  ('negara', 'Azerbaijan', 'Azerbaijan', 'hard'),
  ('kota', 'Reykjavik', 'Reykjavik', 'hard'),
  ('kota', 'Ouagadougou', 'Ouagadougou', 'hard'),
  ('kota', 'Copenhagen', 'Kopenhagen', 'hard'),
  ('kota', 'Marrakech', 'Marrakech', 'hard'),
  ('kota', 'Antananarivo', 'Antananarivo', 'hard'),
  ('tokoh', 'Nietzsche', 'Nietzsche', 'hard'),
  ('tokoh', 'Beethoven', 'Beethoven', 'hard'),
  ('tokoh', 'Shakespeare', 'Shakespeare', 'hard'),
  ('tokoh', 'Pythagoras', 'Pythagoras', 'hard'),
  ('tokoh', 'Michelangelo', 'Michelangelo', 'hard'),
  ('film', 'Interstellar', 'Interstellar', 'hard'),
  ('film', 'The Godfather', 'The Godfather', 'hard'),
  ('film', 'Pulp Fiction', 'Pulp Fiction', 'hard'),
  ('film', 'Oppenheimer', 'Oppenheimer', 'hard'),
  ('film', 'Parasite', 'Parasite', 'hard'),
  ('olahraga', 'Fencing', 'Anggar', 'hard'),
  ('olahraga', 'Equestrian', 'Berkuda', 'hard'),
  ('olahraga', 'Curling', 'Curling', 'hard'),
  ('olahraga', 'Biathlon', 'Biatlon', 'hard'),
  ('olahraga', 'Water Polo', 'Polo Air', 'hard'),
  ('musik', 'Bassoon', 'Basun', 'hard'),
  ('musik', 'Harpsichord', 'Harpsikord', 'hard'),
  ('musik', 'Didgeridoo', 'Didgeridoo', 'hard'),
  ('musik', 'Bagpipes', 'Bagpipe', 'hard'),
  ('musik', 'Theremin', 'Theremin', 'hard'),
  ('anime', 'Evangelion', 'Evangelion', 'hard'),
  ('anime', 'Death Note', 'Death Note', 'hard'),
  ('anime', 'Fullmetal Alchemist', 'Fullmetal Alchemist', 'hard'),
  ('anime', 'Cowboy Bebop', 'Cowboy Bebop', 'hard'),
  ('game', 'The Witcher', 'The Witcher', 'hard')
) AS v(slug, word_en, word_id, difficulty)
JOIN public.categories c ON c.slug = v.slug
ON CONFLICT DO NOTHING;
