-- ============================================================
-- Seed: bulk drawable words (~300 per difficulty)
-- Curated common/drawable nouns, avoids existing seed words.
-- Slugs must match categories in 002_seed_data.sql
-- Duplicates against existing rows are dropped by ON CONFLICT.
-- ============================================================

INSERT INTO public.words (category_id, word_en, word_id, difficulty)
SELECT c.id, v.word_en, v.word_id, v.difficulty
FROM (VALUES
  -- ================= EASY =================
  -- body
  ('benda', 'Hand', 'Tangan', 'easy'),
  ('benda', 'Foot', 'Kaki', 'easy'),
  ('benda', 'Eye', 'Mata', 'easy'),
  ('benda', 'Ear', 'Telinga', 'easy'),
  ('benda', 'Nose', 'Hidung', 'easy'),
  ('benda', 'Mouth', 'Mulut', 'easy'),
  ('benda', 'Hair', 'Rambut', 'easy'),
  ('benda', 'Tooth', 'Gigi', 'easy'),
  ('benda', 'Tongue', 'Lidah', 'easy'),
  ('benda', 'Finger', 'Jari', 'easy'),
  ('benda', 'Head', 'Kepala', 'easy'),
  ('benda', 'Arm', 'Lengan', 'easy'),
  ('benda', 'Leg', 'Tungkai', 'easy'),
  ('benda', 'Knee', 'Lutut', 'easy'),
  ('benda', 'Face', 'Wajah', 'easy'),
  ('benda', 'Lips', 'Bibir', 'easy'),
  ('benda', 'Beard', 'Janggut', 'easy'),
  ('benda', 'Mustache', 'Kumis', 'easy'),
  ('benda', 'Eyebrow', 'Alis', 'easy'),
  ('benda', 'Neck', 'Leher', 'easy'),
  -- clothing
  ('benda', 'Shirt', 'Baju', 'easy'),
  ('benda', 'Pants', 'Celana', 'easy'),
  ('benda', 'Dress', 'Gaun', 'easy'),
  ('benda', 'Skirt', 'Rok', 'easy'),
  ('benda', 'Socks', 'Kaus Kaki', 'easy'),
  ('benda', 'Gloves', 'Sarung Tangan', 'easy'),
  ('benda', 'Scarf', 'Syal', 'easy'),
  ('benda', 'Jacket', 'Jaket', 'easy'),
  ('benda', 'Sweater', 'Sweter', 'easy'),
  ('benda', 'Tie', 'Dasi', 'easy'),
  ('benda', 'Belt', 'Sabuk', 'easy'),
  ('benda', 'Helmet', 'Helm', 'easy'),
  ('benda', 'Boots', 'Sepatu Bot', 'easy'),
  ('benda', 'Sandals', 'Sandal', 'easy'),
  ('benda', 'Slippers', 'Selop', 'easy'),
  ('benda', 'Ring', 'Cincin', 'easy'),
  ('benda', 'Necklace', 'Kalung', 'easy'),
  ('benda', 'Bracelet', 'Gelang', 'easy'),
  ('benda', 'Crown', 'Mahkota', 'easy'),
  ('benda', 'Button', 'Kancing', 'easy'),
  -- household
  ('benda', 'Bowl', 'Mangkuk', 'easy'),
  ('benda', 'Pan', 'Wajan', 'easy'),
  ('benda', 'Pot', 'Panci', 'easy'),
  ('benda', 'Kettle', 'Ceret', 'easy'),
  ('benda', 'Broom', 'Sapu', 'easy'),
  ('benda', 'Mop', 'Pel', 'easy'),
  ('benda', 'Towel', 'Handuk', 'easy'),
  ('benda', 'Soap', 'Sabun', 'easy'),
  ('benda', 'Toothbrush', 'Sikat Gigi', 'easy'),
  ('benda', 'Comb', 'Sisir', 'easy'),
  ('benda', 'Pillow', 'Bantal', 'easy'),
  ('benda', 'Blanket', 'Selimut', 'easy'),
  ('benda', 'Curtain', 'Gorden', 'easy'),
  ('benda', 'Carpet', 'Karpet', 'easy'),
  ('benda', 'Basket', 'Keranjang', 'easy'),
  ('benda', 'Box', 'Kotak', 'easy'),
  ('benda', 'Wallet', 'Dompet', 'easy'),
  ('benda', 'Fan', 'Kipas', 'easy'),
  ('benda', 'Matches', 'Korek Api', 'easy'),
  ('benda', 'Lighter', 'Pemantik', 'easy'),
  ('benda', 'Battery', 'Baterai', 'easy'),
  ('benda', 'Bulb', 'Bohlam', 'easy'),
  ('benda', 'Plug', 'Colokan', 'easy'),
  ('benda', 'Nail', 'Paku', 'easy'),
  ('benda', 'Screw', 'Sekrup', 'easy'),
  ('benda', 'Screwdriver', 'Obeng', 'easy'),
  ('benda', 'Wrench', 'Kunci Inggris', 'easy'),
  ('benda', 'Saw', 'Gergaji', 'easy'),
  ('benda', 'Axe', 'Kapak', 'easy'),
  ('benda', 'Shovel', 'Sekop', 'easy'),
  ('benda', 'Rake', 'Garu', 'easy'),
  ('benda', 'Dustpan', 'Pengki', 'easy'),
  -- furniture
  ('benda', 'Sofa', 'Sofa', 'easy'),
  ('benda', 'Desk', 'Meja Tulis', 'easy'),
  ('benda', 'Shelf', 'Rak', 'easy'),
  ('benda', 'Drawer', 'Laci', 'easy'),
  ('benda', 'Wardrobe', 'Lemari', 'easy'),
  ('benda', 'Stool', 'Bangku', 'easy'),
  ('benda', 'Bench', 'Bangku Panjang', 'easy'),
  ('benda', 'Cabinet', 'Kabinet', 'easy'),
  -- nature
  ('benda', 'Rock', 'Batu', 'easy'),
  ('benda', 'Sand', 'Pasir', 'easy'),
  ('benda', 'Hill', 'Bukit', 'easy'),
  ('benda', 'Island', 'Pulau', 'easy'),
  ('benda', 'Beach', 'Pantai', 'easy'),
  ('benda', 'Forest', 'Hutan', 'easy'),
  ('benda', 'Lake', 'Danau', 'easy'),
  ('benda', 'Waterfall', 'Air Terjun', 'easy'),
  ('benda', 'Volcano', 'Gunung Berapi', 'easy'),
  ('benda', 'Cave', 'Gua', 'easy'),
  ('benda', 'Desert', 'Gurun', 'easy'),
  ('benda', 'Lightning', 'Petir', 'easy'),
  ('benda', 'Wind', 'Angin', 'easy'),
  ('benda', 'Storm', 'Badai', 'easy'),
  ('benda', 'Fog', 'Kabut', 'easy'),
  ('benda', 'Ice', 'Es', 'easy'),
  ('benda', 'Wave', 'Ombak', 'easy'),
  ('benda', 'Bush', 'Semak', 'easy'),
  ('benda', 'Root', 'Akar', 'easy'),
  ('benda', 'Seed', 'Biji', 'easy'),
  ('benda', 'Branch', 'Ranting', 'easy'),
  ('benda', 'Wood', 'Kayu', 'easy'),
  ('benda', 'Mushroom', 'Jamur', 'easy'),
  ('benda', 'Cactus', 'Kaktus', 'easy'),
  ('benda', 'Bamboo', 'Bambu', 'easy'),
  ('benda', 'Sky', 'Langit', 'easy'),
  ('benda', 'Planet', 'Planet', 'easy'),
  ('benda', 'Earth', 'Bumi', 'easy'),
  -- animals
  ('hewan', 'Deer', 'Rusa', 'easy'),
  ('hewan', 'Fox', 'Rubah', 'easy'),
  ('hewan', 'Wolf', 'Serigala', 'easy'),
  ('hewan', 'Zebra', 'Zebra', 'easy'),
  ('hewan', 'Giraffe', 'Jerapah', 'easy'),
  ('hewan', 'Hippo', 'Kuda Nil', 'easy'),
  ('hewan', 'Pig', 'Babi', 'easy'),
  ('hewan', 'Buffalo', 'Kerbau', 'easy'),
  ('hewan', 'Donkey', 'Keledai', 'easy'),
  ('hewan', 'Bat', 'Kelelawar', 'easy'),
  ('hewan', 'Hamster', 'Hamster', 'easy'),
  ('hewan', 'Snail', 'Siput', 'easy'),
  ('hewan', 'Worm', 'Cacing', 'easy'),
  ('hewan', 'Caterpillar', 'Ulat', 'easy'),
  ('hewan', 'Ladybug', 'Kepik', 'easy'),
  ('hewan', 'Grasshopper', 'Belalang', 'easy'),
  ('hewan', 'Dragonfly', 'Capung', 'easy'),
  ('hewan', 'Mosquito', 'Nyamuk', 'easy'),
  ('hewan', 'Fly', 'Lalat', 'easy'),
  ('hewan', 'Cockroach', 'Kecoa', 'easy'),
  ('hewan', 'Scorpion', 'Kalajengking', 'easy'),
  ('hewan', 'Lizard', 'Kadal', 'easy'),
  ('hewan', 'Gecko', 'Cicak', 'easy'),
  ('hewan', 'Shrimp', 'Udang', 'easy'),
  ('hewan', 'Lobster', 'Lobster', 'easy'),
  ('hewan', 'Shark', 'Hiu', 'easy'),
  ('hewan', 'Starfish', 'Bintang Laut', 'easy'),
  ('hewan', 'Seal', 'Anjing Laut', 'easy'),
  ('hewan', 'Walrus', 'Walrus', 'easy'),
  ('hewan', 'Toad', 'Kodok', 'easy'),
  ('hewan', 'Parrot', 'Burung Beo', 'easy'),
  ('hewan', 'Eagle', 'Elang', 'easy'),
  ('hewan', 'Sparrow', 'Pipit', 'easy'),
  ('hewan', 'Crow', 'Gagak', 'easy'),
  ('hewan', 'Pigeon', 'Merpati', 'easy'),
  ('hewan', 'Swan', 'Angsa', 'easy'),
  ('hewan', 'Rooster', 'Ayam Jago', 'easy'),
  ('hewan', 'Turkey', 'Kalkun', 'easy'),
  ('hewan', 'Ostrich', 'Burung Unta', 'easy'),
  ('hewan', 'Woodpecker', 'Pelatuk', 'easy'),
  ('hewan', 'Hummingbird', 'Kolibri', 'easy'),
  -- food
  ('makanan', 'Hotdog', 'Hotdog', 'easy'),
  ('makanan', 'Fries', 'Kentang Goreng', 'easy'),
  ('makanan', 'Taco', 'Taco', 'easy'),
  ('makanan', 'Pasta', 'Pasta', 'easy'),
  ('makanan', 'Salad', 'Salad', 'easy'),
  ('makanan', 'Steak', 'Steik', 'easy'),
  ('makanan', 'Bacon', 'Bacon', 'easy'),
  ('makanan', 'Sausage', 'Sosis', 'easy'),
  ('makanan', 'Omelette', 'Telur Dadar', 'easy'),
  ('makanan', 'Waffle', 'Wafel', 'easy'),
  ('makanan', 'Cookie', 'Kue Kering', 'easy'),
  ('makanan', 'Biscuit', 'Biskuit', 'easy'),
  ('makanan', 'Chocolate', 'Cokelat', 'easy'),
  ('makanan', 'Candy', 'Permen', 'easy'),
  ('makanan', 'Lollipop', 'Lolipop', 'easy'),
  ('makanan', 'Honey', 'Madu', 'easy'),
  ('makanan', 'Jam', 'Selai', 'easy'),
  ('makanan', 'Butter', 'Mentega', 'easy'),
  ('makanan', 'Salt', 'Garam', 'easy'),
  ('makanan', 'Sugar', 'Gula', 'easy'),
  ('makanan', 'Pepper', 'Lada', 'easy'),
  ('makanan', 'Chili', 'Cabai', 'easy'),
  ('makanan', 'Onion', 'Bawang', 'easy'),
  ('makanan', 'Garlic', 'Bawang Putih', 'easy'),
  ('makanan', 'Potato', 'Kentang', 'easy'),
  ('makanan', 'Tomato', 'Tomat', 'easy'),
  ('makanan', 'Carrot', 'Wortel', 'easy'),
  ('makanan', 'Corn', 'Jagung', 'easy'),
  ('makanan', 'Cabbage', 'Kubis', 'easy'),
  ('makanan', 'Broccoli', 'Brokoli', 'easy'),
  ('makanan', 'Cucumber', 'Timun', 'easy'),
  ('makanan', 'Eggplant', 'Terong', 'easy'),
  ('makanan', 'Pumpkin', 'Labu', 'easy'),
  ('makanan', 'Bean', 'Buncis', 'easy'),
  ('makanan', 'Spinach', 'Bayam', 'easy'),
  ('makanan', 'Lettuce', 'Selada', 'easy'),
  ('makanan', 'Coffee', 'Kopi', 'easy'),
  ('makanan', 'Tea', 'Teh', 'easy'),
  ('makanan', 'Juice', 'Jus', 'easy'),
  ('makanan', 'Soda', 'Soda', 'easy'),
  ('makanan', 'Lemonade', 'Limun', 'easy'),
  ('makanan', 'Popsicle', 'Es Loli', 'easy'),
  -- fruits
  ('buah', 'Pear', 'Pir', 'easy'),
  ('buah', 'Peach', 'Persik', 'easy'),
  ('buah', 'Cherry', 'Ceri', 'easy'),
  ('buah', 'Lemon', 'Lemon', 'easy'),
  ('buah', 'Lime', 'Jeruk Nipis', 'easy'),
  ('buah', 'Plum', 'Prem', 'easy'),
  ('buah', 'Apricot', 'Aprikot', 'easy'),
  ('buah', 'Fig', 'Ara', 'easy'),
  ('buah', 'Blueberry', 'Bluberi', 'easy'),
  ('buah', 'Raspberry', 'Rasberi', 'easy'),
  ('buah', 'Blackberry', 'Blackberry', 'easy'),
  ('buah', 'Jackfruit', 'Nangka', 'easy'),
  ('buah', 'Mangosteen', 'Manggis', 'easy'),
  ('buah', 'Salak', 'Salak', 'easy'),
  ('buah', 'Longan', 'Kelengkeng', 'easy'),
  ('buah', 'Passionfruit', 'Markisa', 'easy'),
  ('buah', 'Soursop', 'Sirsak', 'easy'),
  -- vehicles
  ('kendaraan', 'Van', 'Van', 'easy'),
  ('kendaraan', 'Jeep', 'Jip', 'easy'),
  ('kendaraan', 'Firetruck', 'Mobil Pemadam', 'easy'),
  ('kendaraan', 'Tank', 'Tank', 'easy'),
  ('kendaraan', 'Jet', 'Jet', 'easy'),
  ('kendaraan', 'Yacht', 'Kapal Pesiar', 'easy'),
  ('kendaraan', 'Canoe', 'Kano', 'easy'),
  ('kendaraan', 'Kayak', 'Kayak', 'easy'),
  ('kendaraan', 'Raft', 'Rakit', 'easy'),
  ('kendaraan', 'Wheelbarrow', 'Gerobak', 'easy'),
  ('kendaraan', 'Carriage', 'Kereta Kuda', 'easy'),
  ('kendaraan', 'Trolley', 'Troli', 'easy'),
  ('kendaraan', 'Forklift', 'Forklift', 'easy'),
  ('kendaraan', 'Bulldozer', 'Buldoser', 'easy'),
  ('kendaraan', 'Crane', 'Derek', 'easy'),
  ('kendaraan', 'Excavator', 'Ekskavator', 'easy'),
  -- sports
  ('olahraga', 'Baseball', 'Bisbol', 'easy'),
  ('olahraga', 'Cricket', 'Kriket', 'easy'),
  ('olahraga', 'Rugby', 'Rugbi', 'easy'),
  ('olahraga', 'Hockey', 'Hoki', 'easy'),
  ('olahraga', 'Bowling', 'Boling', 'easy'),
  ('olahraga', 'Billiards', 'Bilyar', 'easy'),
  ('olahraga', 'Darts', 'Panah Dart', 'easy'),
  ('olahraga', 'Chess', 'Catur', 'easy'),
  ('olahraga', 'Skiing', 'Ski', 'easy'),
  ('olahraga', 'Skating', 'Seluncur Es', 'easy'),
  ('olahraga', 'Diving', 'Menyelam', 'easy'),
  ('olahraga', 'Rowing', 'Dayung', 'easy'),
  ('olahraga', 'Wrestling', 'Gulat', 'easy'),
  ('olahraga', 'Judo', 'Judo', 'easy'),
  ('olahraga', 'Taekwondo', 'Taekwondo', 'easy'),
  ('olahraga', 'Gymnastics', 'Senam', 'easy'),
  ('olahraga', 'Yoga', 'Yoga', 'easy'),
  -- music
  ('musik', 'Cello', 'Selo', 'easy'),
  ('musik', 'Harmonica', 'Harmonika', 'easy'),
  ('musik', 'Tambourine', 'Rebana', 'easy'),
  ('musik', 'Maracas', 'Marakas', 'easy'),
  ('musik', 'Banjo', 'Banjo', 'easy'),
  ('musik', 'Ukulele', 'Ukulele', 'easy'),
  ('musik', 'Bell', 'Lonceng', 'easy'),
  ('musik', 'Whistle', 'Peluit', 'easy'),
  ('musik', 'Organ', 'Organ', 'easy'),
  ('musik', 'Cymbal', 'Simbal', 'easy'),
  ('musik', 'Gong', 'Gong', 'easy'),
  -- professions
  ('profesi', 'Baker', 'Tukang Roti', 'easy'),
  ('profesi', 'Butcher', 'Tukang Daging', 'easy'),
  ('profesi', 'Barber', 'Tukang Cukur', 'easy'),
  ('profesi', 'Waiter', 'Pelayan', 'easy'),
  ('profesi', 'Cashier', 'Kasir', 'easy'),
  ('profesi', 'Clown', 'Badut', 'easy'),
  ('profesi', 'Magician', 'Pesulap', 'easy'),
  ('profesi', 'Singer', 'Penyanyi', 'easy'),
  ('profesi', 'Dancer', 'Penari', 'easy'),
  ('profesi', 'Painter', 'Pelukis', 'easy'),
  ('profesi', 'Writer', 'Penulis', 'easy'),
  ('profesi', 'Actor', 'Aktor', 'easy'),
  ('profesi', 'King', 'Raja', 'easy'),
  ('profesi', 'Queen', 'Ratu', 'easy'),
  ('profesi', 'Prince', 'Pangeran', 'easy'),
  ('profesi', 'Princess', 'Putri', 'easy'),
  ('profesi', 'Knight', 'Ksatria', 'easy'),
  ('profesi', 'Pirate', 'Bajak Laut', 'easy'),
  ('profesi', 'Ninja', 'Ninja', 'easy'),
  ('profesi', 'Cowboy', 'Koboi', 'easy'),
  ('profesi', 'Wizard', 'Penyihir', 'easy'),
  ('profesi', 'Witch', 'Penyihir Wanita', 'easy'),
  ('profesi', 'Judge', 'Hakim', 'easy'),
  ('profesi', 'Lawyer', 'Pengacara', 'easy'),
  ('profesi', 'Sailor', 'Pelaut', 'easy'),
  ('profesi', 'Fisherman', 'Nelayan', 'easy'),
  ('profesi', 'Miner', 'Penambang', 'easy'),
  ('profesi', 'Gardener', 'Tukang Kebun', 'easy'),
  ('profesi', 'Mechanic', 'Montir', 'easy'),
  ('profesi', 'Plumber', 'Tukang Ledeng', 'easy'),
  ('profesi', 'Carpenter', 'Tukang Kayu', 'easy'),
  ('profesi', 'Dentist', 'Dokter Gigi', 'easy'),
  ('profesi', 'Referee', 'Wasit', 'easy'),
  -- misc objects
  ('benda', 'Flag', 'Bendera', 'easy'),
  ('benda', 'Gift', 'Hadiah', 'easy'),
  ('benda', 'Dice', 'Dadu', 'easy'),
  ('benda', 'Card', 'Kartu', 'easy'),
  ('benda', 'Toy', 'Mainan', 'easy'),
  ('benda', 'Doll', 'Boneka', 'easy'),
  ('benda', 'Teddy Bear', 'Boneka Beruang', 'easy'),
  ('benda', 'Calendar', 'Kalender', 'easy'),
  ('benda', 'Map', 'Peta', 'easy'),
  ('benda', 'Globe', 'Bola Dunia', 'easy'),
  ('benda', 'Binoculars', 'Teropong', 'easy'),
  ('benda', 'Magnet', 'Magnet', 'easy'),
  ('benda', 'Rope', 'Tali', 'easy'),
  ('benda', 'Chain', 'Rantai', 'easy'),
  ('benda', 'Hook', 'Kait', 'easy'),
  ('benda', 'Net', 'Jaring', 'easy'),
  ('benda', 'Cage', 'Kandang', 'easy'),
  ('benda', 'Trophy', 'Piala', 'easy'),
  ('benda', 'Medal', 'Medali', 'easy'),
  ('benda', 'Ticket', 'Tiket', 'easy'),
  ('benda', 'Stamp', 'Perangko', 'easy'),
  ('benda', 'Envelope', 'Amplop', 'easy'),
  ('benda', 'Letter', 'Surat', 'easy'),
  ('benda', 'Newspaper', 'Koran', 'easy'),
  ('benda', 'Magazine', 'Majalah', 'easy'),
  ('benda', 'Notebook', 'Buku Catatan', 'easy'),
  ('benda', 'Pen', 'Pulpen', 'easy'),
  ('benda', 'Eraser', 'Penghapus', 'easy'),
  ('benda', 'Ruler', 'Penggaris', 'easy'),
  ('benda', 'Crayon', 'Krayon', 'easy'),
  ('benda', 'Paint', 'Cat', 'easy'),
  ('benda', 'Glue', 'Lem', 'easy'),
  ('benda', 'Tape', 'Selotip', 'easy'),
  ('benda', 'Stapler', 'Stapler', 'easy'),
  ('benda', 'Clip', 'Klip', 'easy'),

  -- ================= MEDIUM =================
  -- animals
  ('hewan', 'Chimpanzee', 'Simpanse', 'medium'),
  ('hewan', 'Gorilla', 'Gorila', 'medium'),
  ('hewan', 'Orangutan', 'Orangutan', 'medium'),
  ('hewan', 'Sloth', 'Kungkang', 'medium'),
  ('hewan', 'Anteater', 'Pemakan Semut', 'medium'),
  ('hewan', 'Raccoon', 'Rakun', 'medium'),
  ('hewan', 'Skunk', 'Sigung', 'medium'),
  ('hewan', 'Beaver', 'Berang-berang', 'medium'),
  ('hewan', 'Meerkat', 'Meerkat', 'medium'),
  ('hewan', 'Lemur', 'Lemur', 'medium'),
  ('hewan', 'Chinchilla', 'Cincila', 'medium'),
  ('hewan', 'Weasel', 'Musang', 'medium'),
  ('hewan', 'Badger', 'Luak', 'medium'),
  ('hewan', 'Mole', 'Tikus Tanah', 'medium'),
  ('hewan', 'Bison', 'Bison', 'medium'),
  ('hewan', 'Yak', 'Yak', 'medium'),
  ('hewan', 'Llama', 'Llama', 'medium'),
  ('hewan', 'Alpaca', 'Alpaka', 'medium'),
  ('hewan', 'Antelope', 'Antelop', 'medium'),
  ('hewan', 'Gazelle', 'Gazel', 'medium'),
  ('hewan', 'Moose', 'Rusa Besar', 'medium'),
  ('hewan', 'Reindeer', 'Rusa Kutub', 'medium'),
  ('hewan', 'Boar', 'Babi Hutan', 'medium'),
  ('hewan', 'Tapir', 'Tapir', 'medium'),
  ('hewan', 'Hyena', 'Hiena', 'medium'),
  ('hewan', 'Jaguar', 'Jaguar', 'medium'),
  ('hewan', 'Leopard', 'Macan Tutul', 'medium'),
  ('hewan', 'Cheetah', 'Citah', 'medium'),
  ('hewan', 'Panther', 'Panter', 'medium'),
  ('hewan', 'Lynx', 'Lynx', 'medium'),
  ('hewan', 'Bobcat', 'Kucing Hutan', 'medium'),
  ('hewan', 'Cougar', 'Puma', 'medium'),
  ('hewan', 'Ocelot', 'Oselot', 'medium'),
  ('hewan', 'Toucan', 'Tukan', 'medium'),
  ('hewan', 'Pelican', 'Pelikan', 'medium'),
  ('hewan', 'Stork', 'Bangau', 'medium'),
  ('hewan', 'Heron', 'Kuntul', 'medium'),
  ('hewan', 'Kingfisher', 'Raja Udang', 'medium'),
  ('hewan', 'Canary', 'Kenari', 'medium'),
  ('hewan', 'Cockatoo', 'Kakatua', 'medium'),
  ('hewan', 'Macaw', 'Makau', 'medium'),
  ('hewan', 'Vulture', 'Burung Nasar', 'medium'),
  ('hewan', 'Seagull', 'Camar', 'medium'),
  ('hewan', 'Albatross', 'Albatros', 'medium'),
  ('hewan', 'Puffin', 'Puffin', 'medium'),
  ('hewan', 'Emu', 'Emu', 'medium'),
  ('hewan', 'Pheasant', 'Pegar', 'medium'),
  ('hewan', 'Quail', 'Puyuh', 'medium'),
  ('hewan', 'Magpie', 'Murai', 'medium'),
  ('hewan', 'Swordfish', 'Ikan Todak', 'medium'),
  ('hewan', 'Pufferfish', 'Ikan Buntal', 'medium'),
  ('hewan', 'Clownfish', 'Ikan Badut', 'medium'),
  ('hewan', 'Stingray', 'Ikan Pari', 'medium'),
  ('hewan', 'Eel', 'Belut', 'medium'),
  ('hewan', 'Squid', 'Cumi-cumi', 'medium'),
  ('hewan', 'Cuttlefish', 'Sotong', 'medium'),
  ('hewan', 'Barracuda', 'Barakuda', 'medium'),
  ('hewan', 'Manta Ray', 'Pari Manta', 'medium'),
  ('hewan', 'Sea Turtle', 'Penyu', 'medium'),
  ('hewan', 'Coral', 'Karang', 'medium'),
  ('hewan', 'Iguana', 'Iguana', 'medium'),
  ('hewan', 'Komodo', 'Komodo', 'medium'),
  ('hewan', 'Cobra', 'Kobra', 'medium'),
  ('hewan', 'Python', 'Piton', 'medium'),
  ('hewan', 'Anaconda', 'Anakonda', 'medium'),
  ('hewan', 'Tortoise', 'Kura-kura Darat', 'medium'),
  -- food
  ('makanan', 'Lasagna', 'Lasagna', 'medium'),
  ('makanan', 'Ravioli', 'Ravioli', 'medium'),
  ('makanan', 'Risotto', 'Risoto', 'medium'),
  ('makanan', 'Burrito', 'Burito', 'medium'),
  ('makanan', 'Quesadilla', 'Quesadilla', 'medium'),
  ('makanan', 'Nachos', 'Nachos', 'medium'),
  ('makanan', 'Falafel', 'Falafel', 'medium'),
  ('makanan', 'Hummus', 'Hummus', 'medium'),
  ('makanan', 'Kebab', 'Kebab', 'medium'),
  ('makanan', 'Gyro', 'Giros', 'medium'),
  ('makanan', 'Pho', 'Pho', 'medium'),
  ('makanan', 'Ramen', 'Ramen', 'medium'),
  ('makanan', 'Udon', 'Udon', 'medium'),
  ('makanan', 'Tempura', 'Tempura', 'medium'),
  ('makanan', 'Dim Sum', 'Dim Sum', 'medium'),
  ('makanan', 'Spring Roll', 'Lumpia', 'medium'),
  ('makanan', 'Wonton', 'Wonton', 'medium'),
  ('makanan', 'Curry', 'Kari', 'medium'),
  ('makanan', 'Biryani', 'Biryani', 'medium'),
  ('makanan', 'Gumbo', 'Gumbo', 'medium'),
  ('makanan', 'Chowder', 'Sup Krim', 'medium'),
  ('makanan', 'Meatloaf', 'Rolade', 'medium'),
  ('makanan', 'Casserole', 'Kaserol', 'medium'),
  ('makanan', 'Souffle', 'Sufle', 'medium'),
  ('makanan', 'Crepe', 'Krep', 'medium'),
  ('makanan', 'Eclair', 'Eklair', 'medium'),
  ('makanan', 'Muffin', 'Mufin', 'medium'),
  ('makanan', 'Cupcake', 'Kupkek', 'medium'),
  ('makanan', 'Brownie', 'Brownies', 'medium'),
  ('makanan', 'Cheesecake', 'Kue Keju', 'medium'),
  ('makanan', 'Pie', 'Pai', 'medium'),
  ('makanan', 'Tart', 'Tar', 'medium'),
  ('makanan', 'Pretzel', 'Pretzel', 'medium'),
  ('makanan', 'Bagel', 'Bagel', 'medium'),
  ('makanan', 'Toast', 'Roti Panggang', 'medium'),
  ('makanan', 'Porridge', 'Bubur', 'medium'),
  ('makanan', 'Cereal', 'Sereal', 'medium'),
  ('makanan', 'Yogurt', 'Yoghurt', 'medium'),
  ('makanan', 'Smoothie', 'Smuti', 'medium'),
  ('makanan', 'Milkshake', 'Milkshake', 'medium'),
  ('makanan', 'Sundae', 'Sundae', 'medium'),
  ('makanan', 'Soto', 'Soto', 'medium'),
  ('makanan', 'Ketoprak', 'Ketoprak', 'medium'),
  ('makanan', 'Pempek', 'Pempek', 'medium'),
  ('makanan', 'Martabak', 'Martabak', 'medium'),
  ('makanan', 'Klepon', 'Klepon', 'medium'),
  ('makanan', 'Tofu', 'Tahu', 'medium'),
  ('makanan', 'Tempe', 'Tempe', 'medium'),
  ('makanan', 'Kerupuk', 'Kerupuk', 'medium'),
  ('makanan', 'Sambal', 'Sambal', 'medium'),
  -- objects
  ('benda', 'Microscope', 'Mikroskop', 'medium'),
  ('benda', 'Thermometer', 'Termometer', 'medium'),
  ('benda', 'Stopwatch', 'Stopwatch', 'medium'),
  ('benda', 'Calculator', 'Kalkulator', 'medium'),
  ('benda', 'Typewriter', 'Mesin Tik', 'medium'),
  ('benda', 'Projector', 'Proyektor', 'medium'),
  ('benda', 'Speaker', 'Pengeras Suara', 'medium'),
  ('benda', 'Amplifier', 'Amplifier', 'medium'),
  ('benda', 'Turntable', 'Pemutar Piringan', 'medium'),
  ('benda', 'Cassette', 'Kaset', 'medium'),
  ('benda', 'Vinyl', 'Piringan Hitam', 'medium'),
  ('benda', 'Joystick', 'Joystik', 'medium'),
  ('benda', 'Controller', 'Kontroler', 'medium'),
  ('benda', 'Console', 'Konsol', 'medium'),
  ('benda', 'Monitor', 'Monitor', 'medium'),
  ('benda', 'Webcam', 'Webcam', 'medium'),
  ('benda', 'Router', 'Router', 'medium'),
  ('benda', 'Modem', 'Modem', 'medium'),
  ('benda', 'Charger', 'Pengisi Daya', 'medium'),
  ('benda', 'Powerbank', 'Powerbank', 'medium'),
  ('benda', 'Remote', 'Remot', 'medium'),
  ('benda', 'Doorbell', 'Bel Pintu', 'medium'),
  ('benda', 'Alarm', 'Alarm', 'medium'),
  ('benda', 'Siren', 'Sirene', 'medium'),
  ('benda', 'Megaphone', 'Megafon', 'medium'),
  ('benda', 'Lantern', 'Lentera', 'medium'),
  ('benda', 'Torch', 'Obor', 'medium'),
  ('benda', 'Flashlight', 'Senter', 'medium'),
  ('benda', 'Spotlight', 'Lampu Sorot', 'medium'),
  ('benda', 'Firework', 'Kembang Api', 'medium'),
  ('benda', 'Firecracker', 'Petasan', 'medium'),
  ('benda', 'Pliers', 'Tang', 'medium'),
  ('benda', 'Chisel', 'Pahat', 'medium'),
  ('benda', 'Drill', 'Bor', 'medium'),
  ('benda', 'Sandpaper', 'Amplas', 'medium'),
  ('benda', 'Level', 'Waterpas', 'medium'),
  ('benda', 'Tape Measure', 'Meteran', 'medium'),
  ('benda', 'Clamp', 'Penjepit', 'medium'),
  ('benda', 'Anvil', 'Landasan', 'medium'),
  ('benda', 'Furnace', 'Tungku', 'medium'),
  ('benda', 'Grinder', 'Gerinda', 'medium'),
  ('benda', 'Toolbox', 'Kotak Perkakas', 'medium'),
  ('benda', 'Blender', 'Blender', 'medium'),
  ('benda', 'Mixer', 'Mikser', 'medium'),
  ('benda', 'Toaster', 'Pemanggang Roti', 'medium'),
  ('benda', 'Microwave', 'Microwave', 'medium'),
  ('benda', 'Oven', 'Oven', 'medium'),
  ('benda', 'Stove', 'Kompor', 'medium'),
  ('benda', 'Fridge', 'Kulkas', 'medium'),
  ('benda', 'Freezer', 'Freezer', 'medium'),
  ('benda', 'Grater', 'Parutan', 'medium'),
  ('benda', 'Peeler', 'Pengupas', 'medium'),
  ('benda', 'Whisk', 'Kocokan', 'medium'),
  ('benda', 'Rolling Pin', 'Penggilas', 'medium'),
  ('benda', 'Colander', 'Saringan', 'medium'),
  ('benda', 'Ladle', 'Sendok Sayur', 'medium'),
  ('benda', 'Spatula', 'Spatula', 'medium'),
  ('benda', 'Cutting Board', 'Talenan', 'medium'),
  ('benda', 'Corkscrew', 'Pembuka Botol', 'medium'),
  ('benda', 'Can Opener', 'Pembuka Kaleng', 'medium'),
  ('benda', 'Thermos', 'Termos', 'medium'),
  ('benda', 'Teapot', 'Teko', 'medium'),
  ('benda', 'Mug', 'Mug', 'medium'),
  ('benda', 'Jar', 'Toples', 'medium'),
  ('benda', 'Tray', 'Nampan', 'medium'),
  ('benda', 'Napkin', 'Serbet', 'medium'),
  ('benda', 'Straw', 'Sedotan', 'medium'),
  ('benda', 'Chopsticks', 'Sumpit', 'medium'),
  ('benda', 'Apron', 'Celemek', 'medium'),
  -- places
  ('benda', 'Castle', 'Kastil', 'medium'),
  ('benda', 'Palace', 'Istana', 'medium'),
  ('benda', 'Temple', 'Kuil', 'medium'),
  ('benda', 'Church', 'Gereja', 'medium'),
  ('benda', 'Mosque', 'Masjid', 'medium'),
  ('benda', 'Pyramid', 'Piramida', 'medium'),
  ('benda', 'Tower', 'Menara', 'medium'),
  ('benda', 'Bridge', 'Jembatan', 'medium'),
  ('benda', 'Skyscraper', 'Pencakar Langit', 'medium'),
  ('benda', 'Barn', 'Lumbung', 'medium'),
  ('benda', 'Igloo', 'Iglo', 'medium'),
  ('benda', 'Tent', 'Tenda', 'medium'),
  ('benda', 'Hut', 'Gubuk', 'medium'),
  ('benda', 'Cabin', 'Pondok', 'medium'),
  ('benda', 'Mansion', 'Rumah Mewah', 'medium'),
  ('benda', 'Stadium', 'Stadion', 'medium'),
  ('benda', 'Arena', 'Arena', 'medium'),
  ('benda', 'Theater', 'Teater', 'medium'),
  ('benda', 'Cinema', 'Bioskop', 'medium'),
  ('benda', 'Museum', 'Museum', 'medium'),
  ('benda', 'School', 'Sekolah', 'medium'),
  ('benda', 'Factory', 'Pabrik', 'medium'),
  ('benda', 'Prison', 'Penjara', 'medium'),
  ('benda', 'Bank', 'Bank', 'medium'),
  ('benda', 'Hotel', 'Hotel', 'medium'),
  ('benda', 'Restaurant', 'Restoran', 'medium'),
  ('benda', 'Cafe', 'Kafe', 'medium'),
  ('benda', 'Market', 'Pasar', 'medium'),
  ('benda', 'Mall', 'Mal', 'medium'),
  ('benda', 'Airport', 'Bandara', 'medium'),
  ('benda', 'Station', 'Stasiun', 'medium'),
  ('benda', 'Harbor', 'Pelabuhan', 'medium'),
  ('benda', 'Fountain', 'Air Mancur', 'medium'),
  ('benda', 'Statue', 'Patung', 'medium'),
  ('benda', 'Monument', 'Monumen', 'medium'),
  ('benda', 'Gate', 'Gerbang', 'medium'),
  ('benda', 'Fence', 'Pagar', 'medium'),
  ('benda', 'Well', 'Sumur', 'medium'),
  ('benda', 'Dam', 'Bendungan', 'medium'),
  ('benda', 'Hospital', 'Rumah Sakit', 'medium'),
  ('benda', 'Library', 'Perpustakaan', 'medium'),
  -- vehicles
  ('kendaraan', 'Monorail', 'Monorel', 'medium'),
  ('kendaraan', 'Tram', 'Trem', 'medium'),
  ('kendaraan', 'Subway', 'Kereta Bawah Tanah', 'medium'),
  ('kendaraan', 'Cable Car', 'Kereta Gantung', 'medium'),
  ('kendaraan', 'Ferry', 'Feri', 'medium'),
  ('kendaraan', 'Speedboat', 'Perahu Cepat', 'medium'),
  ('kendaraan', 'Jetski', 'Jetski', 'medium'),
  ('kendaraan', 'Hovercraft', 'Hovercraft', 'medium'),
  ('kendaraan', 'Blimp', 'Balon Udara', 'medium'),
  ('kendaraan', 'Hot Air Balloon', 'Balon Udara Panas', 'medium'),
  ('kendaraan', 'Glider', 'Pesawat Layang', 'medium'),
  ('kendaraan', 'Biplane', 'Pesawat Dua Sayap', 'medium'),
  ('kendaraan', 'Seaplane', 'Pesawat Air', 'medium'),
  ('kendaraan', 'Zeppelin', 'Zeppelin', 'medium'),
  ('kendaraan', 'Chariot', 'Kereta Perang', 'medium'),
  ('kendaraan', 'Rickshaw', 'Becak', 'medium'),
  ('kendaraan', 'Tuktuk', 'Bajaj', 'medium'),
  ('kendaraan', 'Gondola', 'Gondola', 'medium'),
  ('kendaraan', 'Snowmobile', 'Mobil Salju', 'medium'),
  ('kendaraan', 'Unicycle', 'Sepeda Roda Satu', 'medium'),
  ('kendaraan', 'Tricycle', 'Sepeda Roda Tiga', 'medium'),
  ('kendaraan', 'Moped', 'Moped', 'medium'),
  ('kendaraan', 'Golf Cart', 'Mobil Golf', 'medium'),
  ('kendaraan', 'Limousine', 'Limosin', 'medium'),
  ('kendaraan', 'Convertible', 'Mobil Atap Terbuka', 'medium'),
  ('kendaraan', 'Pickup', 'Pikap', 'medium'),
  ('kendaraan', 'Minivan', 'Minivan', 'medium'),
  -- pop culture
  ('film', 'Shrek', 'Shrek', 'medium'),
  ('film', 'Aladdin', 'Aladdin', 'medium'),
  ('film', 'Cinderella', 'Cinderella', 'medium'),
  ('film', 'Pinocchio', 'Pinokio', 'medium'),
  ('film', 'Tarzan', 'Tarzan', 'medium'),
  ('film', 'Godzilla', 'Godzilla', 'medium'),
  ('film', 'King Kong', 'King Kong', 'medium'),
  ('film', 'Terminator', 'Terminator', 'medium'),
  ('film', 'Jaws', 'Jaws', 'medium'),
  ('film', 'Alien', 'Alien', 'medium'),
  ('film', 'Gladiator', 'Gladiator', 'medium'),
  ('film', 'Up', 'Up', 'medium'),
  ('film', 'Cars', 'Cars', 'medium'),
  ('film', 'Coco', 'Coco', 'medium'),
  ('film', 'Moana', 'Moana', 'medium'),
  ('film', 'Tangled', 'Tangled', 'medium'),
  ('film', 'Encanto', 'Encanto', 'medium'),
  ('film', 'Wall-E', 'Wall-E', 'medium'),
  ('film', 'Dumbo', 'Dumbo', 'medium'),
  ('film', 'Mulan', 'Mulan', 'medium'),
  ('game', 'Sonic', 'Sonic', 'medium'),
  ('game', 'Mario', 'Mario', 'medium'),
  ('game', 'Zelda', 'Zelda', 'medium'),
  ('game', 'Overwatch', 'Overwatch', 'medium'),
  ('game', 'Halo', 'Halo', 'medium'),
  ('game', 'Sudoku', 'Sudoku', 'medium'),
  ('game', 'Monopoly', 'Monopoli', 'medium'),
  ('game', 'Uno', 'Uno', 'medium'),
  ('game', 'Jenga', 'Jenga', 'medium'),
  ('game', 'Ludo', 'Ludo', 'medium'),
  ('game', 'Domino', 'Domino', 'medium'),
  ('game', 'Checkers', 'Dam', 'medium'),
  ('anime', 'Bleach', 'Bleach', 'medium'),
  ('anime', 'Sailor Moon', 'Sailor Moon', 'medium'),
  ('anime', 'Gundam', 'Gundam', 'medium'),
  ('anime', 'Digimon', 'Digimon', 'medium'),
  ('anime', 'Chainsaw Man', 'Chainsaw Man', 'medium'),
  ('anime', 'Spy x Family', 'Spy x Family', 'medium'),
  ('anime', 'Haikyuu', 'Haikyuu', 'medium'),
  ('anime', 'Tokyo Ghoul', 'Tokyo Ghoul', 'medium'),
  ('anime', 'Hunter x Hunter', 'Hunter x Hunter', 'medium'),
  ('kartun', 'Popeye', 'Popeye', 'medium'),
  ('kartun', 'Garfield', 'Garfield', 'medium'),
  ('kartun', 'Snoopy', 'Snoopy', 'medium'),
  ('kartun', 'Scooby Doo', 'Scooby Doo', 'medium'),
  ('kartun', 'Simpsons', 'Simpsons', 'medium'),
  ('kartun', 'Barbie', 'Barbie', 'medium'),
  ('kartun', 'Winnie the Pooh', 'Winnie the Pooh', 'medium'),
  ('kartun', 'Bugs Bunny', 'Bugs Bunny', 'medium'),
  ('kartun', 'Donald Duck', 'Donal Bebek', 'medium'),

  -- ================= HARD =================
  -- professions
  ('profesi', 'Ornithologist', 'Ahli Burung', 'hard'),
  ('profesi', 'Entomologist', 'Ahli Serangga', 'hard'),
  ('profesi', 'Herpetologist', 'Ahli Reptil', 'hard'),
  ('profesi', 'Ichthyologist', 'Ahli Ikan', 'hard'),
  ('profesi', 'Paleontologist', 'Ahli Paleontologi', 'hard'),
  ('profesi', 'Geologist', 'Ahli Geologi', 'hard'),
  ('profesi', 'Astronomer', 'Astronom', 'hard'),
  ('profesi', 'Astrophysicist', 'Astrofisikawan', 'hard'),
  ('profesi', 'Biochemist', 'Ahli Biokimia', 'hard'),
  ('profesi', 'Microbiologist', 'Ahli Mikrobiologi', 'hard'),
  ('profesi', 'Epidemiologist', 'Ahli Epidemiologi', 'hard'),
  ('profesi', 'Cardiologist', 'Ahli Jantung', 'hard'),
  ('profesi', 'Neurologist', 'Ahli Saraf', 'hard'),
  ('profesi', 'Radiologist', 'Ahli Radiologi', 'hard'),
  ('profesi', 'Psychiatrist', 'Psikiater', 'hard'),
  ('profesi', 'Orthodontist', 'Ortodontis', 'hard'),
  ('profesi', 'Optometrist', 'Optometris', 'hard'),
  ('profesi', 'Physiotherapist', 'Fisioterapis', 'hard'),
  ('profesi', 'Pharmacist', 'Apoteker', 'hard'),
  ('profesi', 'Surveyor', 'Surveyor', 'hard'),
  ('profesi', 'Architect', 'Arsitek', 'hard'),
  ('profesi', 'Electrician', 'Teknisi Listrik', 'hard'),
  ('profesi', 'Locksmith', 'Tukang Kunci', 'hard'),
  ('profesi', 'Blacksmith', 'Pandai Besi', 'hard'),
  ('profesi', 'Goldsmith', 'Pandai Emas', 'hard'),
  ('profesi', 'Cobbler', 'Tukang Sepatu', 'hard'),
  ('profesi', 'Tailor', 'Penjahit', 'hard'),
  ('profesi', 'Weaver', 'Penenun', 'hard'),
  ('profesi', 'Potter', 'Perajin Gerabah', 'hard'),
  ('profesi', 'Sculptor', 'Pematung', 'hard'),
  ('profesi', 'Calligrapher', 'Ahli Kaligrafi', 'hard'),
  ('profesi', 'Cartoonist', 'Kartunis', 'hard'),
  ('profesi', 'Animator', 'Animator', 'hard'),
  ('profesi', 'Composer', 'Komposer', 'hard'),
  ('profesi', 'Conductor', 'Dirigen', 'hard'),
  ('profesi', 'Playwright', 'Penulis Naskah', 'hard'),
  ('profesi', 'Novelist', 'Novelis', 'hard'),
  ('profesi', 'Poet', 'Penyair', 'hard'),
  ('profesi', 'Translator', 'Penerjemah', 'hard'),
  ('profesi', 'Linguist', 'Ahli Bahasa', 'hard'),
  ('profesi', 'Historian', 'Sejarawan', 'hard'),
  ('profesi', 'Economist', 'Ekonom', 'hard'),
  ('profesi', 'Statistician', 'Ahli Statistik', 'hard'),
  ('profesi', 'Accountant', 'Akuntan', 'hard'),
  ('profesi', 'Actuary', 'Aktuaris', 'hard'),
  -- science / tech
  ('teknologi', 'Photosynthesis', 'Fotosintesis', 'hard'),
  ('teknologi', 'Metamorphosis', 'Metamorfosis', 'hard'),
  ('teknologi', 'Osmosis', 'Osmosis', 'hard'),
  ('teknologi', 'Mitosis', 'Mitosis', 'hard'),
  ('teknologi', 'Ecosystem', 'Ekosistem', 'hard'),
  ('teknologi', 'Chromosome', 'Kromosom', 'hard'),
  ('teknologi', 'Molecule', 'Molekul', 'hard'),
  ('teknologi', 'Atom', 'Atom', 'hard'),
  ('teknologi', 'Electron', 'Elektron', 'hard'),
  ('teknologi', 'Nucleus', 'Inti', 'hard'),
  ('teknologi', 'Enzyme', 'Enzim', 'hard'),
  ('teknologi', 'Protein', 'Protein', 'hard'),
  ('teknologi', 'Bacteria', 'Bakteri', 'hard'),
  ('teknologi', 'Virus', 'Virus', 'hard'),
  ('teknologi', 'Vaccine', 'Vaksin', 'hard'),
  ('teknologi', 'Antibody', 'Antibodi', 'hard'),
  ('teknologi', 'Genome', 'Genom', 'hard'),
  ('teknologi', 'Mutation', 'Mutasi', 'hard'),
  ('teknologi', 'Gravity', 'Gravitasi', 'hard'),
  ('teknologi', 'Magnetism', 'Magnetisme', 'hard'),
  ('teknologi', 'Friction', 'Gesekan', 'hard'),
  ('teknologi', 'Momentum', 'Momentum', 'hard'),
  ('teknologi', 'Velocity', 'Kecepatan', 'hard'),
  ('teknologi', 'Frequency', 'Frekuensi', 'hard'),
  ('teknologi', 'Wavelength', 'Panjang Gelombang', 'hard'),
  ('teknologi', 'Refraction', 'Pembiasan', 'hard'),
  ('teknologi', 'Radiation', 'Radiasi', 'hard'),
  ('teknologi', 'Combustion', 'Pembakaran', 'hard'),
  ('teknologi', 'Evaporation', 'Penguapan', 'hard'),
  ('teknologi', 'Condensation', 'Pengembunan', 'hard'),
  ('teknologi', 'Erosion', 'Erosi', 'hard'),
  ('teknologi', 'Magma', 'Magma', 'hard'),
  ('teknologi', 'Fossil', 'Fosil', 'hard'),
  ('teknologi', 'Glacier', 'Gletser', 'hard'),
  ('teknologi', 'Tundra', 'Tundra', 'hard'),
  ('teknologi', 'Savanna', 'Sabana', 'hard'),
  ('teknologi', 'Rainforest', 'Hutan Hujan', 'hard'),
  ('teknologi', 'Tectonic', 'Tektonik', 'hard'),
  -- instruments
  ('benda', 'Sextant', 'Sekstan', 'hard'),
  ('benda', 'Theodolite', 'Teodolit', 'hard'),
  ('benda', 'Micrometer', 'Mikrometer', 'hard'),
  ('benda', 'Caliper', 'Jangka Sorong', 'hard'),
  ('benda', 'Oscilloscope', 'Osiloskop', 'hard'),
  ('benda', 'Voltmeter', 'Voltmeter', 'hard'),
  ('benda', 'Ammeter', 'Amperemeter', 'hard'),
  ('benda', 'Multimeter', 'Multimeter', 'hard'),
  ('benda', 'Spectroscope', 'Spektroskop', 'hard'),
  ('benda', 'Autoclave', 'Otoklaf', 'hard'),
  ('benda', 'Incubator', 'Inkubator', 'hard'),
  ('benda', 'Refractometer', 'Refraktometer', 'hard'),
  ('benda', 'Anemometer', 'Anemometer', 'hard'),
  ('benda', 'Hygrometer', 'Higrometer', 'hard'),
  ('benda', 'Manometer', 'Manometer', 'hard'),
  ('benda', 'Altimeter', 'Altimeter', 'hard'),
  ('benda', 'Odometer', 'Odometer', 'hard'),
  ('benda', 'Tachometer', 'Takometer', 'hard'),
  ('benda', 'Chronometer', 'Kronometer', 'hard'),
  ('benda', 'Pendulum', 'Bandul', 'hard'),
  ('benda', 'Gyrocompass', 'Girokompas', 'hard'),
  ('benda', 'Microtome', 'Mikrotom', 'hard'),
  -- architecture
  ('benda', 'Colonnade', 'Barisan Tiang', 'hard'),
  ('benda', 'Buttress', 'Penopang', 'hard'),
  ('benda', 'Gargoyle', 'Gargoyle', 'hard'),
  ('benda', 'Spire', 'Menara Runcing', 'hard'),
  ('benda', 'Dome', 'Kubah', 'hard'),
  ('benda', 'Minaret', 'Menara Masjid', 'hard'),
  ('benda', 'Obelisk', 'Obelisk', 'hard'),
  ('benda', 'Ziggurat', 'Ziggurat', 'hard'),
  ('benda', 'Pagoda', 'Pagoda', 'hard'),
  ('benda', 'Coliseum', 'Koloseum', 'hard'),
  ('benda', 'Amphitheater', 'Amfiteater', 'hard'),
  ('benda', 'Mausoleum', 'Mausoleum', 'hard'),
  ('benda', 'Cathedral', 'Katedral', 'hard'),
  ('benda', 'Basilica', 'Basilika', 'hard'),
  ('benda', 'Citadel', 'Benteng', 'hard'),
  ('benda', 'Fortress', 'Kubu', 'hard'),
  ('benda', 'Bastion', 'Benteng Pertahanan', 'hard'),
  ('benda', 'Rampart', 'Tembok Benteng', 'hard'),
  ('benda', 'Moat', 'Parit', 'hard'),
  ('benda', 'Drawbridge', 'Jembatan Angkat', 'hard'),
  ('benda', 'Portcullis', 'Gerbang Besi', 'hard'),
  ('benda', 'Turret', 'Menara Kecil', 'hard'),
  -- myth / fantasy
  ('benda', 'Phoenix', 'Feniks', 'hard'),
  ('benda', 'Griffin', 'Griffin', 'hard'),
  ('benda', 'Pegasus', 'Pegasus', 'hard'),
  ('benda', 'Unicorn', 'Unicorn', 'hard'),
  ('benda', 'Centaur', 'Centaur', 'hard'),
  ('benda', 'Minotaur', 'Minotaur', 'hard'),
  ('benda', 'Medusa', 'Medusa', 'hard'),
  ('benda', 'Cyclops', 'Siklop', 'hard'),
  ('benda', 'Hydra', 'Hidra', 'hard'),
  ('benda', 'Kraken', 'Kraken', 'hard'),
  ('benda', 'Leviathan', 'Leviathan', 'hard'),
  ('benda', 'Chimera', 'Kimera', 'hard'),
  ('benda', 'Sphinx', 'Sfinks', 'hard'),
  ('benda', 'Basilisk', 'Basilisk', 'hard'),
  ('benda', 'Werewolf', 'Manusia Serigala', 'hard'),
  ('benda', 'Vampire', 'Vampir', 'hard'),
  ('benda', 'Zombie', 'Zombi', 'hard'),
  ('benda', 'Goblin', 'Goblin', 'hard'),
  ('benda', 'Troll', 'Troll', 'hard'),
  ('benda', 'Ogre', 'Ogre', 'hard'),
  ('benda', 'Gnome', 'Gnome', 'hard'),
  ('benda', 'Elf', 'Peri', 'hard'),
  ('benda', 'Dwarf', 'Kurcaci', 'hard'),
  ('benda', 'Mermaid', 'Putri Duyung', 'hard'),
  ('benda', 'Dragon', 'Naga', 'hard'),
  ('benda', 'Yeti', 'Yeti', 'hard'),
  ('benda', 'Bigfoot', 'Bigfoot', 'hard'),
  ('benda', 'Genie', 'Jin', 'hard'),
  ('benda', 'Ghost', 'Hantu', 'hard'),
  ('benda', 'Valkyrie', 'Valkyrie', 'hard'),
  -- figures
  ('tokoh', 'Aristotle', 'Aristoteles', 'hard'),
  ('tokoh', 'Plato', 'Plato', 'hard'),
  ('tokoh', 'Socrates', 'Socrates', 'hard'),
  ('tokoh', 'Galileo', 'Galileo', 'hard'),
  ('tokoh', 'Copernicus', 'Copernicus', 'hard'),
  ('tokoh', 'Darwin', 'Darwin', 'hard'),
  ('tokoh', 'Tesla', 'Tesla', 'hard'),
  ('tokoh', 'Edison', 'Edison', 'hard'),
  ('tokoh', 'Da Vinci', 'Da Vinci', 'hard'),
  ('tokoh', 'Mozart', 'Mozart', 'hard'),
  ('tokoh', 'Bach', 'Bach', 'hard'),
  ('tokoh', 'Chopin', 'Chopin', 'hard'),
  ('tokoh', 'Picasso', 'Picasso', 'hard'),
  ('tokoh', 'Van Gogh', 'Van Gogh', 'hard'),
  ('tokoh', 'Rembrandt', 'Rembrandt', 'hard'),
  ('tokoh', 'Monet', 'Monet', 'hard'),
  ('tokoh', 'Dali', 'Dali', 'hard'),
  ('tokoh', 'Freud', 'Freud', 'hard'),
  ('tokoh', 'Lincoln', 'Lincoln', 'hard'),
  ('tokoh', 'Churchill', 'Churchill', 'hard'),
  ('tokoh', 'Caesar', 'Caesar', 'hard'),
  ('tokoh', 'Cleopatra', 'Cleopatra', 'hard'),
  ('tokoh', 'Alexander', 'Alexander', 'hard'),
  ('tokoh', 'Columbus', 'Columbus', 'hard'),
  ('tokoh', 'Magellan', 'Magellan', 'hard'),
  ('tokoh', 'Marco Polo', 'Marco Polo', 'hard'),
  ('tokoh', 'Genghis Khan', 'Genghis Khan', 'hard'),
  ('tokoh', 'Confucius', 'Konfusius', 'hard'),
  ('tokoh', 'Buddha', 'Buddha', 'hard'),
  -- geography
  ('kota', 'Timbuktu', 'Timbuktu', 'hard'),
  ('kota', 'Ulaanbaatar', 'Ulaanbaatar', 'hard'),
  ('kota', 'Kathmandu', 'Kathmandu', 'hard'),
  ('kota', 'Tashkent', 'Tashkent', 'hard'),
  ('kota', 'Ljubljana', 'Ljubljana', 'hard'),
  ('kota', 'Bratislava', 'Bratislava', 'hard'),
  ('kota', 'Zagreb', 'Zagreb', 'hard'),
  ('kota', 'Vilnius', 'Vilnius', 'hard'),
  ('kota', 'Tbilisi', 'Tbilisi', 'hard'),
  ('kota', 'Yerevan', 'Yerevan', 'hard'),
  ('kota', 'Bishkek', 'Bishkek', 'hard'),
  ('kota', 'Ashgabat', 'Ashgabat', 'hard'),
  ('kota', 'Dushanbe', 'Dushanbe', 'hard'),
  ('kota', 'Nairobi', 'Nairobi', 'hard'),
  ('kota', 'Casablanca', 'Casablanca', 'hard'),
  ('kota', 'Johannesburg', 'Johannesburg', 'hard'),
  ('negara', 'Turkmenistan', 'Turkmenistan', 'hard'),
  ('negara', 'Bhutan', 'Bhutan', 'hard'),
  ('negara', 'Liechtenstein', 'Liechtenstein', 'hard'),
  ('negara', 'Montenegro', 'Montenegro', 'hard'),
  ('negara', 'Slovenia', 'Slovenia', 'hard'),
  ('negara', 'Croatia', 'Kroasia', 'hard'),
  ('negara', 'Estonia', 'Estonia', 'hard'),
  ('negara', 'Latvia', 'Latvia', 'hard'),
  ('negara', 'Lithuania', 'Lituania', 'hard'),
  ('negara', 'Moldova', 'Moldova', 'hard'),
  ('negara', 'Belarus', 'Belarus', 'hard'),
  ('negara', 'Mongolia', 'Mongolia', 'hard'),
  ('negara', 'Nepal', 'Nepal', 'hard'),
  ('negara', 'Suriname', 'Suriname', 'hard'),
  -- exotic animals
  ('hewan', 'Quetzal', 'Quetzal', 'hard'),
  ('hewan', 'Kakapo', 'Kakapo', 'hard'),
  ('hewan', 'Aye-aye', 'Aye-aye', 'hard'),
  ('hewan', 'Tarsier', 'Tarsius', 'hard'),
  ('hewan', 'Numbat', 'Numbat', 'hard'),
  ('hewan', 'Quoll', 'Quoll', 'hard'),
  ('hewan', 'Bilby', 'Bilby', 'hard'),
  ('hewan', 'Dugong', 'Duyung', 'hard'),
  ('hewan', 'Coelacanth', 'Coelacanth', 'hard'),
  ('hewan', 'Nautilus', 'Nautilus', 'hard'),
  ('hewan', 'Trilobite', 'Trilobit', 'hard'),
  ('hewan', 'Ammonite', 'Amonit', 'hard'),
  ('hewan', 'Horseshoe Crab', 'Belangkas', 'hard'),
  ('hewan', 'Cicada', 'Tonggeret', 'hard'),
  ('hewan', 'Firefly', 'Kunang-kunang', 'hard'),
  ('hewan', 'Termite', 'Rayap', 'hard'),
  ('hewan', 'Silkworm', 'Ulat Sutra', 'hard'),
  ('hewan', 'Locust', 'Belalang Kembara', 'hard'),
  ('hewan', 'Weevil', 'Kumbang Moncong', 'hard'),
  ('hewan', 'Mantis Shrimp', 'Udang Mantis', 'hard'),
  ('hewan', 'Nudibranch', 'Siput Laut', 'hard'),
  ('hewan', 'Seadragon', 'Naga Laut', 'hard'),
  ('hewan', 'Mantis', 'Belalang Sembah', 'hard'),
  ('hewan', 'Angler', 'Ikan Sungut', 'hard'),
  -- exotic food
  ('makanan', 'Bouillabaisse', 'Bouillabaisse', 'hard'),
  ('makanan', 'Cassoulet', 'Cassoulet', 'hard'),
  ('makanan', 'Foie Gras', 'Foie Gras', 'hard'),
  ('makanan', 'Beef Wellington', 'Beef Wellington', 'hard'),
  ('makanan', 'Carbonara', 'Carbonara', 'hard'),
  ('makanan', 'Minestrone', 'Minestrone', 'hard'),
  ('makanan', 'Gazpacho', 'Gazpacho', 'hard'),
  ('makanan', 'Ceviche', 'Ceviche', 'hard'),
  ('makanan', 'Empanada', 'Empanada', 'hard'),
  ('makanan', 'Churros', 'Churros', 'hard'),
  ('makanan', 'Baguette', 'Baguette', 'hard'),
  ('makanan', 'Focaccia', 'Focaccia', 'hard'),
  ('makanan', 'Strudel', 'Strudel', 'hard'),
  ('makanan', 'Panettone', 'Panettone', 'hard'),
  ('makanan', 'Macaroon', 'Makaron', 'hard'),
  ('makanan', 'Cannoli', 'Cannoli', 'hard'),
  ('makanan', 'Panna Cotta', 'Panna Cotta', 'hard'),
  ('makanan', 'Creme Brulee', 'Creme Brulee', 'hard'),
  ('makanan', 'Flan', 'Flan', 'hard'),
  ('makanan', 'Mochi', 'Mochi', 'hard'),
  ('makanan', 'Taiyaki', 'Taiyaki', 'hard'),
  ('makanan', 'Dorayaki', 'Dorayaki', 'hard'),
  ('makanan', 'Onigiri', 'Onigiri', 'hard'),
  ('makanan', 'Takoyaki', 'Takoyaki', 'hard'),
  ('makanan', 'Okonomiyaki', 'Okonomiyaki', 'hard'),
  ('makanan', 'Bibimbap', 'Bibimbap', 'hard'),
  ('makanan', 'Kimchi', 'Kimchi', 'hard'),
  ('makanan', 'Samosa', 'Samosa', 'hard'),
  ('makanan', 'Naan', 'Naan', 'hard'),
  ('makanan', 'Pad Thai', 'Pad Thai', 'hard'),
  ('makanan', 'Tom Yum', 'Tom Yum', 'hard'),
  ('makanan', 'Laksa', 'Laksa', 'hard'),
  -- abstract
  ('benda', 'Infinity', 'Tak Hingga', 'hard'),
  ('benda', 'Yin Yang', 'Yin Yang', 'hard'),
  ('benda', 'Ankh', 'Ankh', 'hard'),
  ('benda', 'Hieroglyph', 'Hieroglif', 'hard'),
  ('benda', 'Rune', 'Rune', 'hard'),
  ('benda', 'Mandala', 'Mandala', 'hard'),
  ('benda', 'Fractal', 'Fraktal', 'hard'),
  ('benda', 'Origami', 'Origami', 'hard'),
  ('benda', 'Mosaic', 'Mosaik', 'hard'),
  ('benda', 'Stained Glass', 'Kaca Patri', 'hard'),
  ('benda', 'Tapestry', 'Permadani', 'hard'),
  ('benda', 'Fresco', 'Fresko', 'hard'),
  ('benda', 'Silhouette', 'Siluet', 'hard'),
  ('benda', 'Prism', 'Prisma', 'hard'),
  ('benda', 'Constellation', 'Rasi Bintang', 'hard'),
  ('benda', 'Galaxy', 'Galaksi', 'hard'),
  ('benda', 'Nebula', 'Nebula', 'hard'),
  ('benda', 'Supernova', 'Supernova', 'hard'),
  ('benda', 'Black Hole', 'Lubang Hitam', 'hard'),
  ('benda', 'Asteroid', 'Asteroid', 'hard'),
  ('benda', 'Meteorite', 'Meteorit', 'hard'),
  ('benda', 'Eclipse', 'Gerhana', 'hard'),
  ('benda', 'Aurora', 'Aurora', 'hard'),
  ('benda', 'Zodiac', 'Zodiak', 'hard'),
  ('benda', 'Labyrinth', 'Labirin', 'hard')
) AS v(slug, word_en, word_id, difficulty)
JOIN public.categories c ON c.slug = v.slug
ON CONFLICT DO NOTHING;
